version: '3.7'

services:
  db:
    image: postgres:14
    container_name: hub_management_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - hub_management_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER}", "-d", "${DB_NAME}", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hub_management_app
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy  # Ensures app waits for db to be healthy
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: db
      DB_PORT: 5432
    networks:
      - hub_management_network
    volumes:
      - .:/app

  swagger-ui:
    image: swaggerapi/swagger-ui:latest
    container_name: swagger_ui
    ports:
      - "8081:8080"
    environment:
      - SWAGGER_JSON=/docs/swagger.yaml
    volumes:
      - ./docs:/docs
    depends_on:
      - app
    networks:
      - hub_management_network

networks:
  hub_management_network:

volumes:
  db_data: