// Code generated by mockery v2.33.2. DO NOT EDIT.

package mocks

import (
	entity "hub_management_service/internal/entity"

	mock "github.com/stretchr/testify/mock"
)

// HubService is an autogenerated mock type for the HubService type
type HubService struct {
	mock.Mock
}

// CreateHub provides a mock function with given fields: hub
func (_m *HubService) CreateHub(hub *entity.Hub) error {
	ret := _m.Called(hub)

	var r0 error
	if rf, ok := ret.Get(0).(func(*entity.Hub) error); ok {
		r0 = rf(hub)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindHubByID provides a mock function with given fields: id
func (_m *HubService) FindHubByID(id uint) (*entity.Hub, error) {
	ret := _m.Called(id)

	var r0 *entity.Hub
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*entity.Hub, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) *entity.Hub); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Hub)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllHubs provides a mock function with given fields:
func (_m *HubService) GetAllHubs() ([]entity.Hub, error) {
	ret := _m.Called()

	var r0 []entity.Hub
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]entity.Hub, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []entity.Hub); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Hub)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SearchHubsByName provides a mock function with given fields: name
func (_m *HubService) SearchHubsByName(name string) ([]entity.Hub, error) {
	ret := _m.Called(name)

	var r0 []entity.Hub
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]entity.Hub, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) []entity.Hub); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Hub)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewHubService creates a new instance of HubService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHubService(t interface {
	mock.TestingT
	Cleanup(func())
}) *HubService {
	mock := &HubService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
